### ISSUE TITLE
Clarify the difference between ```person.first_name``` and ```person[:first_name]```

### ISSUE THREAD

**Issue by harai** [mongoid/mongoid-site#213]
I am creating the first rails application with Mongoid. Very nice framework. Thanks!

One problem I struggled was the diffence between ```person.first_name``` and ```person[:first_name]```.
[The document](http://mongoid.org/en/mongoid/docs/documents.html) implies they are the same and one method is just an alias of the other, but actually they are not.
When trying to get a custom type using ```person[:first_name]``` notation, the returned value is not the custom type, but the raw structure.

I think additional note should be needed to the document to prevent misunderstanding of other users.

**Comment by arthurnn** [comment]
fixed by pr #262
