### ISSUE TITLE
Remove `allow_dynamic_fields` option from the docs

### ISSUE THREAD

**Issue by arthurnn** [mongoid/mongoid-site#232]
[related https://github.com/mongoid/mongoid/issues/3035]

We need to remove `allow_dynamic_fields` from the docs once we release 4.0

**Comment by lucke84** [comment]
It seems it's been removed (see commit ce210797add6543c225a0630cb7f7177f423ea0a) but the deployed version of the website is probably older.

**Comment by arthurnn** [comment]
thanks @lucke84
