### ISSUE TITLE
Is the website up to date ?

### ISSUE THREAD

**Issue by Intrepidd** [mongoid/mongoid-site#265]
Hello,

I wanted to use ``add_to_set`` and after looking at the doc, I remarked the syntax is not correct.

I wanted to fix that but I remarked the syntax is correct in this repo, since commit 5062c7faf (November 10!)

Is mongoid.org outdated ?

Thanks

**Comment by lucke84** [comment]
I think it is out of date.

**Comment by arthurnn** [comment]
Just released a new update to the site.
thanks for reminding me.
