### ISSUE TITLE
Main menu "Docs" item should be "Docs 4.x"

### ISSUE THREAD

**Issue by lucke84** [mongoid/mongoid-site#266]
I've been working with different people on projects that use Mongoid 4.x. A pattern I've seen repeatedly is devs looking for a specific piece of information in the docs, looking in "Docs 3.x" instead of the 4.x. 

As long as this is mostly a mistake of superficiality, I think it wouldn't hurt to make it clearer, by simply adding the "4.x" suffix to the current "Docs" menu item.

**Comment by arthurnn** [comment]
I think, maybe we should try to hide the docs 3.x somewhere else.. and not have it in the main menu.
anyhow, people should be using mongoid 4.0 .

Wanna try to change that UI and send a PR?
thanks

**Comment by lucke84** [comment]
Sure, will do. :)

**Comment by arthurnn** [comment]
thanks
